exclude: "docs|node_modules|migrations|.git|.tox|chart|data|^template/"
default_stages: [ pre-commit ]
fail_fast: true

default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-check
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: uv-sync-post-merge
        name: UV Sync (Post-Merge)
        entry: bash -c 'git diff ORIG_HEAD HEAD --stat | grep -E "uv.lock|pyproject.toml" && uv sync || echo "依賴檔案無變更，跳過 uv sync。"'
        language: system
        stages: [post-merge]
        pass_filenames: false
        always_run: true
        # uv run pre-commit install --hook-type post-merge
