from .platform.klook.script import KLookRunner

PY_CLASS_SCRIPT = {
    # BooksTicketsRunner,
    # CKSMHRunner,
    # CLabRunner,
    # FuBonArtMuseumRunner,
    # HuaShan1914Runner,
    # JamRunner,
    # IBonRunner,
    # KingCarArtRunner,
    # KKDayRunner,
    # KKTixRunner,
    KLookRunner,
    # MoCaTaipeiRunner,
    # MuseumPostRunner,
    # MwrRunner,
    # NCPIRunner,
    # NmhRunner,
    # NpmRunner,
    # NtcArtMuseumRunner,
    # NtmRunner,
    # NtSecRunner,
    # OpenTixRunner,
    # SongShanCulturalParkRunner,
    # TFamRunner,
    # TmcRunner,
    # TwTcRunner,
    # UdnFunLifeRunner,
    # NTCRIRunner,
    # TaipeiExPoParkRunner,
    # NHRMRunner,
    # NTNUArtMuseumRunner,
    # BoPiLiaoRunner,
    # OCAMRunner,
    # NTPCRunner,
}
