from .museums.tfai.script import TFAIRunner

PLATFORM_RUNNERS = {
    # BooksTicketsRunner,
    # CultureExpressRunner,
    # GaCcRunner,
    # IBonRunner,
    # KKDayRunner,
    # KKTixRunner,
    # KLookRunner,
    # OpenTixRunner,
    # UdnFunLifeRunner,
    # ArtEmperorRunner,
    # NTTRunner,
    # ICultureRunner,
}

MUSEUMS_RUNNERS = {
    # CKSMHRunner,
    # CLabRunner,
    # FuBonArtMuseumRunner,
    # HuaShan1914Runner,
    # JamRunner,
    # KingCarArtRunner,
    # MoCaTaipeiRunner,
    # MuseumPostRunner,
    # MwrRunner,
    # NCPIRunner,
    # NmhRunner,
    # NpmRunner,
    # NtcArtMuseumRunner,
    # NtmRunner,
    # NtSecRunner,
    # SongShanCulturalParkRunner,
    # TFamRunner,
    # TmcRunner,
    # TwTcRunner,
    # NTCRIRunner,
    # TaipeiExPoParkRunner,
    # TaipeiZooRunner,
    # NHRMRunner,
    # NTNUArtMuseumRunner,
    # BoPiLiaoRunner,
    # OCAMRunner,
    # NTPCRunner,
    # TncMMMRunner,
    # KdMoFaRunner,
    # N228MMRunner,
    # HongGahRunner,
    # ShungYeArtRunner,
    # YatsenRunner,
    # NrmRunner,
    # ChiPoLinRunner,
    # PactRunner,
    # RedHouseRunner,
    # YoChangArtRunner,
    # KhmRunner,
    # KmFaRunner,
    # Pier2Runner,
    # TcmRunner,
    # KmoaRunner,
    # NTAECRunner,
    # Culture435Runner,
    # TnamMuseumRunner,
    # TnCsEcRunner,
    # MoNTUERunner,
    # AfmcHall1Runner,
    # AfmcHall2Runner,
    # AfmcHall3Runner,
    # AfmcHall4Runner,
    # AfmcHall5Runner,
    # AfmcHall6Runner,
    # AAAArchivesRunner,
    # ArtistVillageRunner,
    # KiShuAnRunner,
    # NMTLRunner,
    # NMTHRunner,
    # ChiayiMMRunner,
    # ChiayiAMRunner,
    # NtMofaRunner,
    # ChCsEcRunner,
    # NhClAcRunner,
    # TtCsEcRunner,
    # AlienRunner,
    # MofiaRunner,
    # IOESinicaRunner,
    # HistorySinicaRunner,
    # HKMRunner,
    # JuMingRunner,
    # TyCgRunner,
    # PTAMRunner,
    # HcccArtRunner,
    # TcamRunner,
    # TAMRunner,
    # CCAMRunner,
    # CyccRunner,
    # ELandAMRunner,
    # HCAMRunner,
    # AS241Runner,
    # PT1936Runner,
    # PTCAMRunner,
    # MoMaTainanRunner,
    # CZHRunner,
    TFAIRunner,
    # HuaLien1913Runner,
    # SSHMRunner,
    # FuZhong15Runner,
    # XZCACRunner,
}

GALLERIES_RUNNERS = {
    # CapitalArtRunner,
    # RuoMuRunner,
    # YiYunRunner,
    # MindSetArtRunner,
    # Dac99Runner,
    # WhiteStoneRunner,
    # XiZhiTangRunner,
    # CG1839Runner,
    # SoKaArtRunner,
    # NWACRunner,
}

ALL_RUNNERS = list(PLATFORM_RUNNERS) + list(MUSEUMS_RUNNERS) + list(GALLERIES_RUNNERS)
