
name: update-exhibition

permissions:
  contents: write
  pull-requests: write
  
on:
  workflow_dispatch:
  schedule:
  #  0 0,8,16 * * *
    - cron: '0 0,8,16 * * *'
  pull_request:
    branches:
      - "deploy" 
    paths:
      - ".github/workflows/update_exhibition.yml"
  push:
    branches:
      - "deploy"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-process:
    runs-on: ubuntu-latest
    steps:
      - name: set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Taipei"
    
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          ref: 'deploy'
        
      - name: setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - uses: actions/cache@v3
        name: init cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        env:
          PIP_DEFAULT_TIMEOUT: 100
      
          
      - name: execute py script
        run: python run_all_script.py
        env:
          IMGUR_API_CLIENT_ID: ${{ secrets.IMGUR_API_CLIENT_ID }}
          IMGUR_API_CLIENT_SECRET: ${{ secrets.IMGUR_API_CLIENT_SECRET }}
          LINE_NOTIFY_API: ${{ secrets.LINE_NOTIFY_API }}
          SENTRY_SDK_DNS: ${{ secrets.SENTRY_SDK_DNS }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          SCRAPE_DO_API_KEY: ${{ secrets.SCRAPE_DO_API_KEY }}
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local --unset-all "http.https://github.com/.extraheader"
          git add -A
          git commit -m "update data/*.json" -a
      
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy 
      
      
