name: update-async-exhibition

permissions:
  contents: write
  pull-requests: write

env:
  BRANCH: "auto/data-update"
  TZ: "Asia/Taipei"

on:
  workflow_dispatch:
  schedule:
    #  0 0,8,16 * * *
    - cron: '30 0,8,16 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-process:
    runs-on: ubuntu-latest
    steps:
      - name: set timezone
        uses: szenius/set-timezone@1f9716b0f7120e344f0c62bb7b1ee98819aefd42
        with:
          timezoneLinux: "Asia/Taipei"

      - name: checkout repo content
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: "auto/data-update"

      - name: skip if recent push
        if: steps.check_push.outputs.skip == 'true'
        run: echo "⏭️ Skip execution due to recent push"

      - name: setup python 3.12 with uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --no-dev

      - name: run async script with uv
        run: |
          source .venv/bin/activate
          uv run python run_all_async_script.py
        env:
          IMGUR_API_CLIENT_ID: ${{ secrets.IMGUR_API_CLIENT_ID }}
          IMGUR_API_CLIENT_SECRET: ${{ secrets.IMGUR_API_CLIENT_SECRET }}
          SENTRY_SDK_DNS: ${{ secrets.SENTRY_SDK_DNS }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          SCRAPE_DO_API_KEY: ${{ secrets.SCRAPE_DO_API_KEY }}
          IS_DEBUG: ${{ vars.IS_DEBUG }}
          PROXY_POOL: ${{ secrets.PROXY_POOL }}

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if ! git diff --cached --quiet; then
              git commit -m "update data/*.json from async process"
          else
              echo "No changes to commit. Skipping..."
          fi

      - name: push changes
        uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "auto/data-update"


