name: update-async-exhibition

permissions:
  contents: write
  pull-requests: write

env:
  BRANCH: "auto/data-update"
  TZ: "Asia/Taipei"

on:
  workflow_dispatch:
  schedule:
    #  0 0,8,16 * * *
    - cron: '30 0,8,16 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-process:
    runs-on: ubuntu-latest
    steps:
      - name: set timezone with Asia/Taipei
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime
          echo "Asia/Taipei" | sudo tee /etc/timezone
          sudo dpkg-reconfigure -f noninteractive tzdata
      - name: check timezone
        run: timedatectl

      - name: checkout repo content
        uses: actions/checkout@v6.0.2
        with:
          ref: "auto/data-update"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: skip if recent push
        if: steps.check_push.outputs.skip == 'true'
        run: echo "⏭️ Skip execution due to recent push"

      - name: setup python 3.12 with uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --no-dev --frozen

      - name: run async script with uv
        run: uv run --no-sync python run_all_async_script.py
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          SENTRY_SDK_DNS: ${{ secrets.SENTRY_SDK_DNS }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          SCRAPE_DO_API_KEY: ${{ secrets.SCRAPE_DO_API_KEY }}
          IS_DEBUG: ${{ vars.IS_DEBUG }}
          PROXY_POOL: ${{ secrets.PROXY_POOL }}

      - name: commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if ! git diff --cached --quiet; then
              git commit -m "update data/*.json from async process"
              git push origin auto/data-update
          else
              echo "No changes to commit. Skipping..."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



