name: update-async-exhibition

permissions:
  contents: write
  pull-requests: write

env:
  BRANCH: "auto/data-update"

on:
  workflow_dispatch:
  schedule:
    #  0 0,8,16 * * *
    - cron: '0 0,8,16 * * *'
  pull_request:
    branches:
      - "auto/data-update"
    paths:
      - ".github/workflows/update_async_exhibition.yml"
  push:
    branches:
      - "auto/data-update"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-process:
    runs-on: ubuntu-latest
    steps:
      - name: set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Taipei"

      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          ref: "auto/data-update"

      - name: check recent manual push
        id: check_push
        run: |
          FILE=".github/last_push_time.txt"
          if [ -f "$FILE" ]; then
            last_push=$(cat $FILE)
            now=$(date +%s)
            diff=$(( (now - last_push) / 3600 ))
            echo "⏱️ 時差：$diff 小時"
            if [ "$diff" -lt 7 ]; then
              echo "最近 $diff 小時內有 push，跳過這次自動任務"
              echo "skip=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          else
            echo "沒有記錄檔，繼續執行"
          fi
          echo "skip=false" >> $GITHUB_OUTPUT
      - name: skip if recent push
        if: steps.check_push.outputs.skip == 'true'
        run: echo "⏭️ Skip execution due to recent push"

      - name: setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - uses: actions/cache@v3
        name: init cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        env:
          PIP_DEFAULT_TIMEOUT: 100

      - name: execute py async script
        run: python run_all_async_script.py
        env:
          IMGUR_API_CLIENT_ID: ${{ secrets.IMGUR_API_CLIENT_ID }}
          IMGUR_API_CLIENT_SECRET: ${{ secrets.IMGUR_API_CLIENT_SECRET }}
          SENTRY_SDK_DNS: ${{ secrets.SENTRY_SDK_DNS }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          SCRAPE_DO_API_KEY: ${{ secrets.SCRAPE_DO_API_KEY }}
          IS_DEBUG: ${{ vars.IS_DEBUG }}

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local --unset-all "http.https://github.com/.extraheader"
          git add -A
          git commit -m "update data/*.json from async process" -a

      - name: update push timestamp
        if: github.event_name == 'push'
        run: |
          echo $(date +%s) > .github/last_push_time.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/last_push_time.txt
          git commit -m "update last push timestamp" || echo "No changes"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "auto/data-update"


