
name: update-exhibition

permissions:
  contents: write
  pull-requests: write
  
on:
  workflow_dispatch:
  schedule:
    - cron: '* 4 * * *'
  pull_request:
    branches:
      - "develop" 
    paths:
      - ".github/workflows/update_exhibition.yml"
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          ref: 'develop'
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        run: python run_all_script.py
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local --unset-all "http.https://github.com/.extraheader"
          git add -A
          git commit -m "update data" -a
      
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop 
      
      
